language: en-US

reviews:
  profile: chill
  path_filters:
    - "!target/**"
    - "!*.class"
  high_level_summary: true
  poem: true
  sequence_diagrams: true
  collapse_walkthrough: true
  auto_review:
    enabled: true
    drafts: false